SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

-- schema name is `migrationtest`.
DROP SCHEMA IF EXISTS migrationtest;
CREATE SCHEMA migrationtest;
USE migrationtest;

CREATE TABLE users (
  id INTEGER NOT NULL,
  email VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  update_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE profiles (
  id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  update_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);
